name: CI

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  unix:
    name: compile - Ubuntu
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build-opts: [ "-DUSE_THREADS=ON", "-DUSE_THREADS=OFF" ]

    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: mkdir build && cd build && cmake ${{matrix.build-opts}} ..
    - name: Build
      run: cmake --build build

  mac:
    name: compile - MacOS
    runs-on: macos-latest

    strategy:
      matrix:
        build-opts: [ "-DUSE_THREADS=ON", "-DUSE_THREADS=OFF" ]

    steps:
    - uses: actions/checkout@v1
    - name: Dependancies
      run: brew install openssl
    - name: Configure
      run: mkdir build && cd build && cmake ${{matrix.build-opts}} -D OPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1 ..
    - name: Build
      run: cmake --build build

  win:
    name: compile - windows
    runs-on: windows-latest

    strategy:
      matrix:
        build-opts: [ "-DUSE_THREADS=ON", "-DUSE_THREADS=OFF" ]

    steps:
    - uses: actions/checkout@v1
    - name: Dependancies
      run: |
        mkdir build; cd build
        Invoke-WebRequest -Uri https://mirror.firedaemon.com/OpenSSL/openssl-1.1.1e-dev.zip -OutFile openssl.zip
        Expand-Archive openssl.zip
    - name: Configure
      run: cd build; cmake ${{matrix.build-opts}} -D OPENSSL_ROOT_DIR="$pwd\openssl\openssl-1.1\x64" ..
    - name: Build
      run: cmake --build build
